# -*- coding: utf-8 -*-
"""script2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qpa_XFpUOu29-ry1Me19-81v8BedB3VW
"""

import requests
import lxml
from bs4 import BeautifulSoup

result = requests.get("https://www.fiches-auto.fr/avis/")
contents=result.content
soup = BeautifulSoup(contents,"lxml")
classes=soup.find_all("a",{"class":"liste_ft"})

hrefs=[]
for link in classes:
    href = link.get("href")
    hrefs.append(href)
    print(href)

n = len(hrefs) // 3
part1 = hrefs[:n]
part2 = hrefs[n:2*n]
part3 = hrefs[2*n:]

# Print the three parts
print(part1)
print(part2)
print(part3)

comments=[]
modeles=[]
marques=[]
years=[]

import re
nn="https://www.fiches-auto.fr/"
urlss=[]
for l in part2:
  ll=nn+l
  print("llll", ll)

  result = requests.get(ll)
  contents=result.content
  soup = BeautifulSoup(contents,"lxml")
  links=soup.find_all("a",{"class":"liste_ft"})
  mar=soup.find("font",{"color":"#DF0301"})
  m=mar.get_text()
  print("marc :",m)
  print(len(links))
  for o in links:
    mmm = o.text
    match = re.search(r'Avis\s+(.*?)\s+\d{4}', mmm)

    if match:
        result = match.group(1)
        modele=result.strip()
        print("Voir le modele :",modele)
    else:
        print("No match found.")
    year = re.findall('Avis.*?(\d{4})', mmm)[0]
    print("year :",year)
    href = o.get("href")
    p="https://www.fiches-auto.fr"
    href=p+href
    result = requests.get(href)
    contents=result.content
    soup = BeautifulSoup(contents,"lxml")
    #########################################################################################################
    lin=soup.find_all("a",{"style":"color:#000"})
    for p in lin:
        href = p.get("href")
        p="https://www.fiches-auto.fr"
        href=p+href
        result = requests.get(href)
        contents=result.content
        soup = BeautifulSoup(contents,"lxml")
        avis=soup.find("p",{"style":"margin:0; "})
        if avis is None:
          print("avis mot found")
        else:

          text=avis.get_text()
          #print("text ---------------------------------------------------------- ",text)
          comments.append(text)
          modeles.append(modele)
          marques.append(m)
          years.append(year)

print(len(comments))
print(len(modeles))
print(len(marques))
print(len(years))

import openpyxl

wb = openpyxl.Workbook()
ws = wb.active

ws.append(['makes', 'modeles', 'comments','years'])

for i in range(len(comments)):
    ws.append([marques[i], modeles[i], comments[i],years[i]])

wb.save('data2.xlsx')